name: Build LaTeX templates
on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * 1' #Â Run at 0400 every Monday.
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Letter
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_letter.tex
            latexmk_use_xelatex: true
      - name: Upload Letter PDF
        uses: actions/upload-artifact@v3
        with:
            name: PDF
            path: template_letter.pdf
      - name: Compile Portrait Poster
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_poster_portrait.tex
            latexmk_use_xelatex: true
      - name: Upload Portrait Poster PDF
        uses: actions/upload-artifact@v3
        with:
            name: PDF
            path: template_poster_portrait.pdf
      - name: Compile Landscape Poster
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_poster_landscape.tex
            latexmk_use_xelatex: true
      - name: Upload Portrait Poster PDF
        uses: actions/upload-artifact@v3
        with:
            name: PDF
            path: template_poster_landscape.pdf